<?php
use Migrations\AbstractSeed;

/**
 * Competencies seed.
 */
class CompetenciesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
                      ['text'    => 'Achievement Focus',
                      'maximum_level'   =>'5',
                      'description' => "is generating results by assuming responsibility for one's performance and the correctness of one's interventions, and recognising opportunities and acting efficiently at the appropriate moment and within the given deadlines.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Client Focus',
                      'maximum_level'   =>'5',
                      'description' => "is based on the ability to understand internal/external clients’ (e.g. Committees, working groups, country representatives, etc.,) needs and concerns in the short to long-term and to provide sound recommendations and/or solutions.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Team work & Leadership',
                      'maximum_level'   =>'5',
                      'description' => "implies working co-operatively with others, being a part of a team, and assuming the role of leader of a team. Ability to work not only with their own teams but also with teams and groups across and outside the Organisation. Therefore they need to work together effectively with interdependent goals and common values and norms to foster a collaborative environment and drive teams in the same direction.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Organisational Alignment',
                      'maximum_level'   =>'5',
                      'description' => "is the ability and willingness to align one’s own behaviour with the needs, priorities, and goals of the Organisation, and to act in ways that promote the Organisation’s goals or meet organisational needs. Organisational Alignment means focusing on the Organisation's mission before one's own preferences or professional priorities.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Flexible thinking',
                      'maximum_level'   =>'5',
                      'description' => "involves the ability to effectively adapt to a variety of situations, individuals or groups. It is based on the ability to understand and appreciate different and opposing perspectives on an issue, to adapt an approach as the requirements of a situation change, and to change or easily accept changes in one’s own organisational or job requirements.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Organisational Knowledge',
                      'maximum_level'   =>'5',
                      'description' => "is the ability to understand the power relationships within the Organisation and with other organisations. It includes the ability to understand the formal rules and structures including the ability to identify who the real decision-makers are as well as the individuals who can influence them.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Diplomatic Sensitivity',
                      'maximum_level'   =>'5',
                      'description' => "implies understanding other people. It includes the ability to hear accurately and understand unspoken, partly expressed thoughts, feelings and concerns of others. Included in this competency is an emphasis on cross-cultural sensitivity. Proficiency in Diplomatic Sensitivity requires the ability to keep one’s emotions under control and restrain negative actions when faced with opposition or hostility from others or when working under stress.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Influencing',
                      'maximum_level'   =>'5',
                      'description' => "implies an intention to convince others in an honest, respectful and sensitive manner in order to get them to go along with one’s objectives. It can also be the desire to have a specific impact or effect on others.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Negotiating',
                      'maximum_level'   =>'5',
                      'description' => "involves the ability to work towards win-win outcomes. At lower levels, this competency assumes an understanding of one’s counterparts and how to respond to them during negotiations. At the higher levels, the competency reflects a focus to achieve value-added results.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Drafting Skills',
                      'maximum_level'   =>'5',
                      'description' => "are based on the ability to respectfully communicate ideas and information (often technical) in writing to ensure that information and messages are understood and have the desired impact.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Analytical thinking',
                      'maximum_level'   =>'5',
                      'description' => "is the ability to identify patterns across situations that are not obviously related, and to identify key or underlying issues in complex situations.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Customer Experience: Articulates the desired customer experience',
                      'maximum_level'   =>'5',
                      'description' => "This technical capability is about defining what the customer experience should be in order to meet corporate objectives and achieve customer advocacy. It is also about the delivery of activities that deliver the desired customer experience through effective customer journeys.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Customer Experience: Delivers the customer experience and customer satisfaction',
                      'maximum_level'   =>'5',
                      'description' => "This technical capability is about defining what the customer experience should be in order to meet corporate objectives and achieve customer advocacy. It is also about the delivery of activities that deliver the desired customer experience through effective customer journeys.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Product Management: Innovates value propositions',
                      'maximum_level'   =>'5',
                      'description' => "This technical capability deals with the planning, forecasting, production and marketing of a product, proposition or portfolio of products, throughout a product lifecycle.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Product Management: Manages value propositions, products and services',
                      'maximum_level'   =>'5',
                      'description' => "This technical capability deals with the planning, forecasting, production and marketing of a product, proposition or portfolio of products, throughout a product lifecycle.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Monitoring and Measuring Effectiveness: Measures the effectiveness of marketing activities',
                      'maximum_level'   =>'5',
                      'description' => "This technical capability is about identifying appropriate metrics and ensuring that all marketing activities, whether generated by the organisation or the customer, are monitored on an ongoing basis and measured for their effectiveness. Data and insights produced are then interpreted and used to achieve improvements in the future.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Monitoring and Measuring Effectiveness: Uses analytics to explain the success or failure of marketing activities',
                      'maximum_level'   =>'5',
                      'description' => "This technical capability is about identifying appropriate metrics and ensuring that all marketing activities, whether generated by the organisation or the customer, are monitored on an ongoing basis and measured for their effectiveness. Data and insights produced are then interpreted and used to achieve improvements in the future.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Monitoring and Measuring Effectiveness: Monitors digital and social reputation',
                      'maximum_level'   =>'5',
                      'description' => "This technical capability is about identifying appropriate metrics and ensuring that all marketing activities, whether generated by the organisation or the customer, are monitored on an ongoing basis and measured for their effectiveness. Data and insights produced are then interpreted and used to achieve improvements in the future.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Algorithms',
                      'maximum_level'   =>'4',
                      'description' => "This technical capability deals with Tree, Graph, simple greedy and divide and conquer algorithms, and the ability to understand the relevance of the levels of this competency.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Source Code Version Control',
                      'maximum_level'   =>'4',
                      'description' => "This technical capability deals with the knowledge of distributed VCS systems and if the developer has tried out Bzr/Mercurial/Darcs/Git.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Automated Testing',
                      'maximum_level'   =>'4',
                      'description' => "This technical capability deals with the understanding and ability to setup automated functional, load/performance and UI tests.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Problem Decomposition',
                      'maximum_level'   =>'4',
                      'description' => "This technical capability deals with the  use of appropriate data structures and algorithms and the ability to come up with generic/object-oriented code that encapsulate aspects of the problem that are subject to change.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Systems Decomposition',
                      'maximum_level'   =>'4',
                      'description' => "This technical capability deals with the ability to visualize and design complex systems with multiple product lines and integrations with external systems. Also, the programmer should be able to design operations support systems like monitoring, reporting, fail overs etc.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Defensive Coding',
                      'maximum_level'   =>'4',
                      'description' => "This technical capability deals with the interest in setting up one's own library to help with defensive coding, and writing unit tests that simulate faults.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Error Handling',
                      'maximum_level'   =>'4',
                      'description' => "This deals with the technical capability to write codes to detect possible exception before, maintain consistent exception handling strategy in all layers of code, and coming up with guidelines on exception handling for entire system.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Requirement Gathering',
                      'maximum_level'   =>'4',
                      'description' => "This deals with the technical capability to suggest better alternatives and flows to given requirements based on experience.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Blogs',
                      'maximum_level'   =>'4',
                      'description' => "This includes the maintainance or the interest in maintainance of a blog in which personal insights and thoughts on programming are shared.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Source tree organization',
                      'maximum_level'   =>'4',
                      'description' => "Physical layout of source tree matches logical hierarchy and organization. The directory names and organization provide insights into the design of the system.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'code organization within a file',
                      'maximum_level'   =>'4',
                      'description' => "This includes the technical capability to organize code in a well documented file. It typically includes a license header, summary, well commented, consistent white space usage features.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Developing Talent',
                      'maximum_level'   =>'5',
                      'description' => "means fostering an environment that will encourage professional and personal growth and the transfer of knowledge to future talent.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Strategic Networking',
                      'maximum_level'   =>'5',
                      'description' => "involves working to build and maintain friendly, trustworthy and open internal and external relationships and networks with people who are, or might become, important actors in achieving strategic-related goals.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Strategic Thinking',
                      'maximum_level'   =>'5',
                      'description' => "is the ability to develop a broad, big-picture view of the Organisation and its mission. Competitive advantage and threats, industry trends, emerging technology, market opportunities, stakeholder focus – Strategic Thinking is where these all come together. Strategic Thinking keeps individuals and groups focused and helps decide where to invest critical resources. It includes the ability to link long-range visions and concepts to daily work.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['text'    => 'Managing Resources',
                      'maximum_level'   =>'5',
                      'description' => "is about understanding human, financial, and operational resource issues to make decisions aimed at building and planning efficient project workflows, and at improving overall organisational performance.",
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),]
        ];

        $table = $this->table('competencies');
        $table->insert($data)->save();
    }
}
