<?php
use Migrations\AbstractSeed;

/**
 * JobDesignationCompetencies seed.
 */
class JobDesignationCompetenciesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
                      ['competency_id' =>'1',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'1',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'1',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'2',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'2',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'2',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'3',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'3',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'3',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'4',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'4',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'4',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'5',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'5',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'5',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'6',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'6',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'6',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'7',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'7',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'7',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'8',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'8',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'8',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'9',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'9',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'9',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'10',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'11',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'12',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'13',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'14',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'15',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'16',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'17',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'18',
                      'job_designation_id' => '3',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'19',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'20',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'21',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'21',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'22',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'23',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'23',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'24',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'25',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'26',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'26',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'27',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'28',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'29',
                      'job_designation_id' => '1',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'29',
                      'job_designation_id' => '2',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'30',
                      'job_designation_id' => '4',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'31',
                      'job_designation_id' => '4',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'32',
                      'job_designation_id' => '4',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),],
                      ['competency_id' =>'33',
                      'job_designation_id' => '4',
                      'created' => date('Y-m-d H:i:s'),
                      'modified'=> date('Y-m-d H:i:s'),]
        ];

        $table = $this->table('job_designation_competencies');
        $table->insert($data)->save();
    }
}
